package Vista;

import Modelo.Autor;
import Modelo.AutorDAO;
import Modelo.Libro;
import Modelo.LibroDAO;
import Modelo.Prestamo;
import Modelo.PrestamoDAO;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class Sistema extends javax.swing.JFrame {

    Autor au = new Autor();
    AutorDAO audao = new AutorDAO();
    Libro li = new Libro();
    LibroDAO lidao = new LibroDAO();
    Prestamo pr = new Prestamo();
    PrestamoDAO prdao = new PrestamoDAO();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        AutoCompleteDecorator.decorate(cbxAutorLibro);
        AutoCompleteDecorator.decorate(cbxCodiliPrestamo);
        lidao.ConsultarAutor(cbxAutorLibro);
        prdao.ConsultarISBN(cbxCodiliPrestamo);
        
    }

    public void ListarAutores() {
        List<Autor> ListaAu = audao.ListarAutores();
        modelo = (DefaultTableModel) TableAutor.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListaAu.size(); i++) {
            ob[0] = ListaAu.get(i).getCodigo();
            ob[1] = ListaAu.get(i).getNombre();
            ob[2] = ListaAu.get(i).getApellido();
            
            modelo.addRow(ob);
        }
        TableAutor.setModel(modelo);
    }

    public void ListarLibros() {
        List<Libro> ListarLI = lidao.ListarLibros();
        modelo = (DefaultTableModel) TableLibro.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < ListarLI.size(); i++) {
            ob[0] = ListarLI.get(i).getISBN();
            ob[1] = ListarLI.get(i).getTitulo();
            ob[2] = ListarLI.get(i).getAutor();
            ob[3] = ListarLI.get(i).getValorprestamo();
            modelo.addRow(ob);
        }
        TableLibro.setModel(modelo);
    }

    public void ListarPrestamos() {
        List<Prestamo> Listarpr = prdao.ListarPrestamos();
        modelo = (DefaultTableModel) TablePrestamo.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < Listarpr.size(); i++) {
            ob[0] = Listarpr.get(i).getNuprestamo();
            ob[1] = Listarpr.get(i).getFechap();
            ob[2] = Listarpr.get(i).getDescripcion();
            ob[3] = Listarpr.get(i).getCodigoli();
            ob[4] = Listarpr.get(i).getCantidad();
            ob[5] = Listarpr.get(i).getFechae();
            modelo.addRow(ob);
        }
        TablePrestamo.setModel(modelo);
    }

    public void LimpiarTable() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnLibro = new javax.swing.JButton();
        btnPrestamo = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnGenerarReporteA = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoAutor = new javax.swing.JTextField();
        txtNombreAutor = new javax.swing.JTextField();
        txtApellidoAutor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAutor = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtActualizarAutor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIsbnLibro = new javax.swing.JTextField();
        txtTituloLibro = new javax.swing.JTextField();
        txtValorpestamoLibro = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableLibro = new javax.swing.JTable();
        btnGenerarReporteL = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        cbxAutorLibro = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNumeroPrestamo = new javax.swing.JTextField();
        txtFechapPrestamo = new javax.swing.JTextField();
        txtDescripcionPrestamo = new javax.swing.JTextField();
        txtCantidadPrestamo = new javax.swing.JTextField();
        txtFechaePrestamo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablePrestamo = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        btnGenerarReporteP = new javax.swing.JButton();
        cbxCodiliPrestamo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Clientes.png"))); // NOI18N
        jButton1.setText("AUTOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLibro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pdf.png"))); // NOI18N
        btnLibro.setText("LIBRO");
        btnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroActionPerformed(evt);
            }
        });

        btnPrestamo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/money.png"))); // NOI18N
        btnPrestamo.setText("PRESTAMO");
        btnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel15)
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(btnLibro)
                .addGap(54, 54, 54)
                .addComponent(btnPrestamo)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 570));

        btnGenerarReporteA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/print.png"))); // NOI18N
        btnGenerarReporteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteAActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Apellido");

        TableAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido"
            }
        ));
        TableAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAutorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableAutor);
        if (TableAutor.getColumnModel().getColumnCount() > 0) {
            TableAutor.getColumnModel().getColumn(0).setMinWidth(50);
            TableAutor.getColumnModel().getColumn(1).setMinWidth(100);
            TableAutor.getColumnModel().getColumn(2).setMinWidth(50);
        }

        jButton5.setText("Agregar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Eliminar");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtActualizarAutor.setText("Actualizar");
        txtActualizarAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtActualizarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoAutor)
                            .addComponent(txtNombreAutor)
                            .addComponent(txtApellidoAutor)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(txtActualizarAutor))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGenerarReporteA)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGenerarReporteA))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApellidoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(txtActualizarAutor))
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ISBN");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Titulo");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Autor");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Valor del préstamo");

        txtTituloLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloLibroActionPerformed(evt);
            }
        });

        TableLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Titulo", "Autor", "Valor del prestamo"
            }
        ));
        TableLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableLibroMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableLibro);
        if (TableLibro.getColumnModel().getColumnCount() > 0) {
            TableLibro.getColumnModel().getColumn(0).setMinWidth(25);
            TableLibro.getColumnModel().getColumn(1).setMinWidth(100);
            TableLibro.getColumnModel().getColumn(2).setMinWidth(100);
            TableLibro.getColumnModel().getColumn(3).setMinWidth(25);
        }

        btnGenerarReporteL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/print.png"))); // NOI18N
        btnGenerarReporteL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteLActionPerformed(evt);
            }
        });

        jButton10.setText("Agregar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Actualizar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Eliminar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        cbxAutorLibro.setEditable(true);
        cbxAutorLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAutorLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTituloLibro)
                            .addComponent(txtIsbnLibro)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(txtValorpestamoLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(cbxAutorLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(btnGenerarReporteL)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addComponent(txtIsbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorpestamoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10)
                            .addComponent(jButton11))
                        .addGap(18, 18, 18)
                        .addComponent(jButton12))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGenerarReporteL)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Numero Préstamo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Fecha Prestamo");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Descripción");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Codigo Libro");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Cantidad");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Fecha Entrega");

        TablePrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Préstamo", "Fecha Prestamo", "Descripción", "Código Libro", "Cantidad", "Fecha Entrega"
            }
        ));
        TablePrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePrestamoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablePrestamo);
        if (TablePrestamo.getColumnModel().getColumnCount() > 0) {
            TablePrestamo.getColumnModel().getColumn(0).setMinWidth(25);
            TablePrestamo.getColumnModel().getColumn(1).setMinWidth(25);
            TablePrestamo.getColumnModel().getColumn(2).setMinWidth(100);
            TablePrestamo.getColumnModel().getColumn(3).setMinWidth(25);
            TablePrestamo.getColumnModel().getColumn(4).setMinWidth(25);
            TablePrestamo.getColumnModel().getColumn(5).setMinWidth(25);
        }

        jButton14.setText("Agregar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Actualizar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Eliminar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        btnGenerarReporteP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/print.png"))); // NOI18N
        btnGenerarReporteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReportePActionPerformed(evt);
            }
        });

        cbxCodiliPrestamo.setEditable(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(txtNumeroPrestamo)
                    .addComponent(txtFechapPrestamo)
                    .addComponent(txtDescripcionPrestamo)
                    .addComponent(txtCantidadPrestamo)
                    .addComponent(txtFechaePrestamo)
                    .addComponent(cbxCodiliPrestamo, 0, 140, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton15)
                        .addGap(44, 44, 44)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(btnGenerarReporteP)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(txtNumeroPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechapPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcionPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(5, 5, 5)
                        .addComponent(cbxCodiliPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaePrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerarReporteP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton14)
                                .addComponent(jButton15)
                                .addComponent(jButton16)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 960, 420));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 289, -1, 140));

        jPanel5.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/espe.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 960, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLibroActionPerformed

    private void btnGenerarReporteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteAActionPerformed
        // TODO add your handling code here:

        pdf();
        LimpiarTable();
    }//GEN-LAST:event_btnGenerarReporteAActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!"".equals(txtCodigoAutor.getText()) || !"".equals(txtNombreAutor.getText()) || !"".equals(txtApellidoAutor.getText()) ) {
            au.setCodigo(Integer.parseInt(txtCodigoAutor.getText()));
            au.setNombre(txtNombreAutor.getText());
            au.setApellido(txtApellidoAutor.getText());
            
            audao.RegistrarAutores(au);
            LimpiarTable();
            LimpiarAutores();
            ListarAutores();
            JOptionPane.showMessageDialog(null, "Autor Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LimpiarTable();
        ListarAutores();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TableAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAutorMouseClicked
        // TODO add your handling code here:
        int fila = TableAutor.rowAtPoint(evt.getPoint());
        txtCodigoAutor.setText(TableAutor.getValueAt(fila, 0).toString());
        txtNombreAutor.setText(TableAutor.getValueAt(fila, 1).toString());
        txtApellidoAutor.setText(TableAutor.getValueAt(fila, 2).toString());
        
    }//GEN-LAST:event_TableAutorMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtCodigoAutor.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar?");
            if (pregunta == 0) {
                int codigo = Integer.parseInt(txtCodigoAutor.getText());
                audao.ElimarAutores(codigo);
                LimpiarTable();
                LimpiarAutores();
                ListarAutores();

            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtActualizarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarAutorActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtCodigoAutor.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(txtCodigoAutor.getText()) && !"".equals(txtNombreAutor.getText()) && !"".equals(txtApellidoAutor.getText())  ) {
                au.setCodigo(Integer.parseInt(txtCodigoAutor.getText()));
                au.setNombre(txtNombreAutor.getText());
                au.setApellido(txtApellidoAutor.getText());
                
                audao.ModificarAutores(au);
                LimpiarTable();
                LimpiarAutores();
                ListarAutores();
            } else {
                JOptionPane.showMessageDialog(null, "No deben haber campos vacios");
            }
        }
    }//GEN-LAST:event_txtActualizarAutorActionPerformed

    private void btnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroActionPerformed
        // TODO add your handling code here:

        LimpiarTable();
        ListarLibros();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnLibroActionPerformed

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
        // TODO add your handling code here:
        LimpiarTable();
        ListarPrestamos();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtIsbnLibro.getText()) || !"".equals(txtTituloLibro.getText()) || !"".equals(cbxAutorLibro.getSelectedItem()) || !"".equals(txtValorpestamoLibro.getText())) {
            li.setISBN(Integer.parseInt(txtIsbnLibro.getText()));
            li.setTitulo(txtTituloLibro.getText());
            li.setAutor(cbxAutorLibro.getSelectedItem().toString());
            li.setValorprestamo(Double.parseDouble(txtValorpestamoLibro.getText()));
            lidao.RegistrarLibros(li);
            LimpiarTable();
            LimpiarLibros();
            ListarLibros();
            JOptionPane.showMessageDialog(null, "Libro Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos");
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtIsbnLibro.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar?");
            if (pregunta == 0) {
                int ISBN = Integer.parseInt(txtIsbnLibro.getText());
                lidao.ElimarLibros(ISBN);
                LimpiarTable();
                LimpiarLibros();
                ListarLibros();

            }
        }


    }//GEN-LAST:event_jButton12ActionPerformed

    private void TableLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableLibroMouseClicked
        // TODO add your handling code here:
        int fila = TableLibro.rowAtPoint(evt.getPoint());
        txtIsbnLibro.setText(TableLibro.getValueAt(fila, 0).toString());
        txtTituloLibro.setText(TableLibro.getValueAt(fila, 1).toString());
        cbxAutorLibro.setSelectedItem(TableLibro.getValueAt(fila, 2).toString());
        txtValorpestamoLibro.setText(TableLibro.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_TableLibroMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtIsbnLibro.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(txtIsbnLibro.getText()) && !"".equals(txtTituloLibro.getText()) && !"".equals(cbxAutorLibro.getSelectedItem()) && !"".equals(txtValorpestamoLibro.getText())) {
                li.setISBN(Integer.parseInt(txtIsbnLibro.getText()));
                li.setTitulo(txtTituloLibro.getText());
                li.setAutor(cbxAutorLibro.getSelectedItem().toString());
                li.setValorprestamo(Double.parseDouble(txtValorpestamoLibro.getText()));
                lidao.ModificarLibros(li);
                JOptionPane.showMessageDialog(null, "Actualizado con éxito");
                LimpiarTable();
                LimpiarLibros();
                ListarLibros();
            } else {
                JOptionPane.showMessageDialog(null, "No deben haber campos vacios");
            }
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnGenerarReporteLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteLActionPerformed
        // TODO add your handling code here:
        pdfLibro();
        LimpiarTable();
    }//GEN-LAST:event_btnGenerarReporteLActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtNumeroPrestamo.getText()) || !"".equals(txtFechapPrestamo.getText()) || !"".equals(txtDescripcionPrestamo.getText()) || !"".equals(cbxCodiliPrestamo.getSelectedItem()) || !"".equals(txtCantidadPrestamo.getText()) || !"".equals(txtFechaePrestamo.getText())) {
            pr.setNuprestamo(Integer.parseInt(txtNumeroPrestamo.getText()));
            pr.setFechap(txtFechapPrestamo.getText());
            pr.setDescripcion(txtDescripcionPrestamo.getText());
            pr.setCodigoli(Integer.parseInt(cbxCodiliPrestamo.getSelectedItem().toString()));
            pr.setCantidad(Integer.parseInt(txtCantidadPrestamo.getText()));
            pr.setFechae(txtFechaePrestamo.getText());
            prdao.RegistrarPrestamos(pr);

            LimpiarTable();
            LimpiarPrestamos();
            ListarPrestamos();
            JOptionPane.showMessageDialog(null, "Prestamo Registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Llenar todos los campos");
        }

    }//GEN-LAST:event_jButton14ActionPerformed

    private void cbxAutorLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAutorLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAutorLibroActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

        if (!"".equals(txtNumeroPrestamo.getText())) {
            int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar?");
            if (pregunta == 0) {
                int nprestamo = Integer.parseInt(txtNumeroPrestamo.getText());
                prdao.ElimarNprestamo(nprestamo);
                LimpiarTable();
                LimpiarPrestamos();
                ListarPrestamos();

            }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void TablePrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePrestamoMouseClicked
        // TODO add your handling code here:

        int fila = TablePrestamo.rowAtPoint(evt.getPoint());
        txtNumeroPrestamo.setText(TablePrestamo.getValueAt(fila, 0).toString());
        txtFechapPrestamo.setText(TablePrestamo.getValueAt(fila, 1).toString());
        txtDescripcionPrestamo.setText(TablePrestamo.getValueAt(fila, 2).toString());
        cbxCodiliPrestamo.setSelectedItem(TablePrestamo.getValueAt(fila, 3).toString());
        txtCantidadPrestamo.setText(TablePrestamo.getValueAt(fila, 4).toString());
        txtFechaePrestamo.setText(TablePrestamo.getValueAt(fila, 5).toString());

    }//GEN-LAST:event_TablePrestamoMouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtNumeroPrestamo.getText())) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {

            if (!"".equals(txtNumeroPrestamo.getText()) && !"".equals(txtFechapPrestamo.getText()) && !"".equals(txtDescripcionPrestamo.getText()) && !"".equals(cbxCodiliPrestamo.getSelectedItem()) && !"".equals(txtCantidadPrestamo.getText()) && !"".equals(txtFechaePrestamo.getText())) {
                pr.setNuprestamo(Integer.parseInt(txtNumeroPrestamo.getText()));
                pr.setFechap(txtFechapPrestamo.getText());
                pr.setDescripcion(txtDescripcionPrestamo.getText());
                pr.setCodigoli(Integer.parseInt(cbxCodiliPrestamo.getSelectedItem().toString()));
                pr.setCantidad(Integer.parseInt(txtCantidadPrestamo.getText()));
                pr.setFechae(txtFechaePrestamo.getText());

                prdao.ModificarPrestamos(pr);
                JOptionPane.showMessageDialog(null, "Actualizado con éxito");
                LimpiarTable();
                LimpiarPrestamos();
                ListarPrestamos();
            } else {
                JOptionPane.showMessageDialog(null, "No deben haber campos vacios");
            }
        }

    }//GEN-LAST:event_jButton15ActionPerformed

    private void btnGenerarReportePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReportePActionPerformed
        // TODO add your handling code here:

        pdfPrestamo();
        LimpiarTable();
    }//GEN-LAST:event_btnGenerarReportePActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAutor;
    private javax.swing.JTable TableLibro;
    private javax.swing.JTable TablePrestamo;
    private javax.swing.JButton btnGenerarReporteA;
    private javax.swing.JButton btnGenerarReporteL;
    private javax.swing.JButton btnGenerarReporteP;
    private javax.swing.JButton btnLibro;
    private javax.swing.JButton btnPrestamo;
    private javax.swing.JComboBox<String> cbxAutorLibro;
    private javax.swing.JComboBox<String> cbxCodiliPrestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton txtActualizarAutor;
    private javax.swing.JTextField txtApellidoAutor;
    private javax.swing.JTextField txtCantidadPrestamo;
    private javax.swing.JTextField txtCodigoAutor;
    private javax.swing.JTextField txtDescripcionPrestamo;
    private javax.swing.JTextField txtFechaePrestamo;
    private javax.swing.JTextField txtFechapPrestamo;
    private javax.swing.JTextField txtIsbnLibro;
    private javax.swing.JTextField txtNombreAutor;
    private javax.swing.JTextField txtNumeroPrestamo;
    private javax.swing.JTextField txtTituloLibro;
    private javax.swing.JTextField txtValorpestamoLibro;
    // End of variables declaration//GEN-END:variables

    private void LimpiarAutores() {
        txtCodigoAutor.setText("");
        txtNombreAutor.setText("");
        txtApellidoAutor.setText("");
        

    }

    private void LimpiarLibros() {
        txtIsbnLibro.setText("");
        txtTituloLibro.setText("");
        cbxAutorLibro.setSelectedItem("");
        txtValorpestamoLibro.setText("");

    }

    private void LimpiarPrestamos() {
        txtNumeroPrestamo.setText("");
        txtFechapPrestamo.setText("");
        txtDescripcionPrestamo.setText("");
        cbxCodiliPrestamo.setSelectedItem("");
        txtCantidadPrestamo.setText("");
        txtFechaePrestamo.setText("");

    }

    private void pdf() {

        try {
            FileOutputStream archivo;
            File file = new File("src/Reportes/venta.pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/Img/espe.png");

            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLUE);
            fecha.add(Chunk.NEWLINE);
            Date date = new Date();
            fecha.add("Fecha: " + new SimpleDateFormat("dd-MM-yyyy").format(date) + "\n\n");

            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumnaEncabezado);
            Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);

            Encabezado.addCell(img);

            String nombrep = "Proyecto parcial uno";
            String motivo = "Generación de Reporte";

            Encabezado.addCell("");
            Encabezado.addCell(nombrep + "\n\n" + motivo);
            Encabezado.addCell(fecha);
            doc.add(Encabezado);

            Paragraph aut = new Paragraph();
            aut.add(Chunk.NEWLINE);
            aut.add("Datos de los autores" + "\n\n");
            doc.add(aut);

            PdfPTable tablaaut = new PdfPTable(3);
            tablaaut.setWidthPercentage(100);
            tablaaut.getDefaultCell().setBorder(0);
            float[] Columnaaut = new float[]{20f, 50f, 30f};
            tablaaut.setWidths(Columnaaut);
            tablaaut.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell aut1 = new PdfPCell(new Phrase(""));
            PdfPCell aut2 = new PdfPCell(new Phrase(""));
            PdfPCell aut3 = new PdfPCell(new Phrase("\n"));
            aut1.setBorder(0);
            aut2.setBorder(0);
            aut3.setBorder(0);
            tablaaut.addCell(aut1);
            tablaaut.addCell(aut2);
            tablaaut.addCell(aut3);
            tablaaut.addCell(txtCodigoAutor.getText());
            tablaaut.addCell(txtNombreAutor.getText());
            tablaaut.addCell(txtApellidoAutor.getText());

            doc.add(tablaaut);

            // Mostrar Datos de las tablas
            PdfPTable tablacont = new PdfPTable(3);
            tablacont.setWidthPercentage(100);
            tablacont.getDefaultCell().setBorder(0);
            float[] Columnacont = new float[]{10f, 30f, 30f};
            tablacont.setWidths(Columnacont);
            tablacont.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell cont1 = new PdfPCell(new Phrase("Codigo"));
            PdfPCell cont2 = new PdfPCell(new Phrase("Nombre"));
            PdfPCell cont3 = new PdfPCell(new Phrase("Apellido\n\n"));
            cont1.setBorder(0);
            cont2.setBorder(0);
            cont3.setBorder(0);
            tablacont.addCell(cont1);
            tablacont.addCell(cont2);
            tablacont.addCell(cont3);
            for (int i = 0; i < TableAutor.getRowCount(); i++) {
                String Codigo = TableAutor.getValueAt(i, 0).toString();
                String Nombre = TableAutor.getValueAt(i, 1).toString();
                String Apellido = TableAutor.getValueAt(i, 2).toString();

                tablacont.addCell(Codigo);
                tablacont.addCell(Nombre);
                tablacont.addCell(Apellido);
            }
            doc.add(tablacont);

            doc.close();
            archivo.close();
            Desktop.getDesktop().open(file);

        } catch (DocumentException | IOException e) {
            System.out.println(e.toString());
        }
    }

    
    private void pdfLibro() {

    try {
        FileOutputStream archivo;
        File file = new File("src/Reportes/venta.pdf");
        archivo = new FileOutputStream(file);
        Document doc = new Document();
        PdfWriter.getInstance(doc, archivo);
        doc.open();
        Image img = Image.getInstance("src/Img/espe.png");

        Paragraph fecha = new Paragraph();
        Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLUE);
        fecha.add(Chunk.NEWLINE);
        Date date = new Date();
        fecha.add("Fecha: " + new SimpleDateFormat("dd-MM-yyyy").format(date) + "\n\n");

        PdfPTable Encabezado = new PdfPTable(4);
        Encabezado.setWidthPercentage(100);
        Encabezado.getDefaultCell().setBorder(0);
        float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
        Encabezado.setWidths(ColumnaEncabezado);
        Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);

        Encabezado.addCell(img);

        String nombrep = "Proyecto parcial uno";
        String motivo = "Generación de Reporte";

        Encabezado.addCell("");
        Encabezado.addCell(nombrep + "\n\n" + motivo);
        Encabezado.addCell(fecha);
        doc.add(Encabezado);

        Paragraph aut = new Paragraph();
        aut.add(Chunk.NEWLINE);
        aut.add("Datos de los Libros" + "\n\n");
        doc.add(aut);

        PdfPTable tablali = new PdfPTable(4);
        tablali.setWidthPercentage(100);
        tablali.getDefaultCell().setBorder(0);
        float[] Columnaaut = new float[]{20f, 50f, 30f, 30f};
        tablali.setWidths(Columnaaut);
        tablali.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell li1 = new PdfPCell(new Phrase(""));
        PdfPCell li2 = new PdfPCell(new Phrase(""));
        PdfPCell li3 = new PdfPCell(new Phrase(""));
        PdfPCell li4 = new PdfPCell(new Phrase("\n"));
        li1.setBorder(0);
        li2.setBorder(0);
        li3.setBorder(0);
        li4.setBorder(0);
        tablali.addCell(li1);
        tablali.addCell(li2);
        tablali.addCell(li3);
        tablali.addCell(li4);
        tablali.addCell(txtIsbnLibro.getText());
        tablali.addCell(txtTituloLibro.getText());
        //tablali.addCell(cbxAutorLibro.getSelectedItem().toString());
        tablali.addCell(txtValorpestamoLibro.getText());

        doc.add(tablali);

        
        PdfPTable tablacontli = new PdfPTable(4);
        tablacontli.setWidthPercentage(100);
        tablacontli.getDefaultCell().setBorder(0);
        float[] Columnacont = new float[]{10f, 30f, 30f, 30f};
        tablacontli.setWidths(Columnacont);
        tablacontli.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell contli1 = new PdfPCell(new Phrase("ISBN"));
        PdfPCell contli2 = new PdfPCell(new Phrase("Titulo"));
        PdfPCell contli3 = new PdfPCell(new Phrase("Autor"));
        PdfPCell contli4 = new PdfPCell(new Phrase("Valor Prestamo\n\n"));
        contli1.setBorder(0);
        contli2.setBorder(0);
        contli3.setBorder(0);
        contli4.setBorder(0);
        tablacontli.addCell(contli1);
        tablacontli.addCell(contli2);
        tablacontli.addCell(contli3);
        tablacontli.addCell(contli4);
        for (int i = 0; i < TableLibro.getRowCount(); i++) {
            String ISBN = TableLibro.getValueAt(i, 0).toString();
            String Titulo = TableLibro.getValueAt(i, 1).toString();
            String Autor = TableLibro.getValueAt(i, 2).toString();
            String Valorprestamo = TableLibro.getValueAt(i, 3).toString();

            tablacontli.addCell(ISBN);
            tablacontli.addCell(Titulo);
            tablacontli.addCell(Autor);
            tablacontli.addCell(Valorprestamo);
        }
        doc.add(tablacontli);

        
        Paragraph reporteCruzado = new Paragraph();
        reporteCruzado.add(Chunk.NEWLINE);
        reporteCruzado.add("\n\nReporte Cruzado" + "\n\n");
        doc.add(reporteCruzado);

        PdfPTable tablaCruzado = new PdfPTable(2); 
        tablaCruzado.setWidthPercentage(100);
        tablaCruzado.getDefaultCell().setBorder(0);
        float[] ColumnaCruzado = new float[]{30f, 30f};
        tablaCruzado.setWidths(ColumnaCruzado);
        tablaCruzado.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell cruzado1 = new PdfPCell(new Phrase("Autor"));
        PdfPCell cruzado2 = new PdfPCell(new Phrase("Cantidad de Libros\n\n"));
        cruzado1.setBorder(0);
        cruzado2.setBorder(0);
        tablaCruzado.addCell(cruzado1);
        tablaCruzado.addCell(cruzado2);

        
        Map<String, Integer> authorBookCount = new HashMap<>();
        for (int i = 0; i < TableLibro.getRowCount(); i++) {
            String Autor = TableLibro.getValueAt(i, 2).toString();
            authorBookCount.put(Autor, authorBookCount.getOrDefault(Autor, 0) + 1);
        }

        
        for (Map.Entry<String, Integer> entry : authorBookCount.entrySet()) {
            tablaCruzado.addCell(entry.getKey());
            tablaCruzado.addCell(entry.getValue().toString());
        }
        
        doc.add(tablaCruzado);

        doc.close();
        archivo.close();
        Desktop.getDesktop().open(file);

    } catch (DocumentException | IOException e) {
        System.out.println(e.toString());
    }
}

    
    private void pdfPrestamo() {
    try {
        FileOutputStream archivo;
        File file = new File("src/Reportes/venta.pdf");
        archivo = new FileOutputStream(file);
        Document doc = new Document();
        PdfWriter.getInstance(doc, archivo);
        doc.open();
        Image img = Image.getInstance("src/Img/espe.png");

        Paragraph fecha = new Paragraph();
        Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLUE);
        fecha.add(Chunk.NEWLINE);
        Date date = new Date();
        fecha.add("Fecha: " + new SimpleDateFormat("dd-MM-yyyy").format(date) + "\n\n");

        PdfPTable Encabezado = new PdfPTable(4);
        Encabezado.setWidthPercentage(100);
        Encabezado.getDefaultCell().setBorder(0);
        float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
        Encabezado.setWidths(ColumnaEncabezado);
        Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);

        Encabezado.addCell(img);

        String nombrep = "Proyecto parcial uno";
        String motivo = "Generación de Reporte";

        Encabezado.addCell("");
        Encabezado.addCell(nombrep + "\n\n" + motivo);
        Encabezado.addCell(fecha);
        doc.add(Encabezado);

        Paragraph aut = new Paragraph();
        aut.add(Chunk.NEWLINE);
        aut.add("Datos de los Prestamos" + "\n\n");
        doc.add(aut);

        PdfPTable tablapr = new PdfPTable(6);
        tablapr.setWidthPercentage(100);
        tablapr.getDefaultCell().setBorder(0);
        float[] Columnaaut = new float[]{40f, 35f, 30f, 30f, 20f, 30f};
        tablapr.setWidths(Columnaaut);
        tablapr.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell pr1 = new PdfPCell(new Phrase(""));
        PdfPCell pr2 = new PdfPCell(new Phrase(""));
        PdfPCell pr3 = new PdfPCell(new Phrase(""));
        PdfPCell pr4 = new PdfPCell(new Phrase(""));
        PdfPCell pr5 = new PdfPCell(new Phrase(""));
        PdfPCell pr6 = new PdfPCell(new Phrase("\n"));
        pr1.setBorder(0);
        pr2.setBorder(0);
        pr3.setBorder(0);
        pr4.setBorder(0);
        pr5.setBorder(0);
        pr6.setBorder(0);
        tablapr.addCell(pr1);
        tablapr.addCell(pr2);
        tablapr.addCell(pr3);
        tablapr.addCell(pr4);
        tablapr.addCell(pr5);
        tablapr.addCell(pr6);
        tablapr.addCell(txtNumeroPrestamo.getText());
        tablapr.addCell(txtFechapPrestamo.getText());
        tablapr.addCell(txtDescripcionPrestamo.getText());
        //tablapr.addCell(cbxCodiliPrestamo.getSelectedItem().toString());
        tablapr.addCell(txtCantidadPrestamo.getText());
        tablapr.addCell(txtFechaePrestamo.getText());

        doc.add(tablapr);

        
        PdfPTable tablacontpr = new PdfPTable(6);
        tablacontpr.setWidthPercentage(100);
        tablacontpr.getDefaultCell().setBorder(0);
        float[] Columnacont = new float[]{40f, 35f, 30f, 30f, 20f, 30f};
        tablacontpr.setWidths(Columnacont);
        tablacontpr.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell contpr1 = new PdfPCell(new Phrase("Numero Prestamo"));
        PdfPCell contpr2 = new PdfPCell(new Phrase("Fecha Prestamo"));
        PdfPCell contpr3 = new PdfPCell(new Phrase("Descripcion"));
        PdfPCell contpr4 = new PdfPCell(new Phrase("Codigo Libro"));
        PdfPCell contpr5 = new PdfPCell(new Phrase("Cantidad"));
        PdfPCell contpr6 = new PdfPCell(new Phrase("Fecha Entrega\n\n"));
        contpr1.setBorder(0);
        contpr2.setBorder(0);
        contpr3.setBorder(0);
        contpr4.setBorder(0);
        contpr5.setBorder(0);
        contpr6.setBorder(0);
        tablacontpr.addCell(contpr1);
        tablacontpr.addCell(contpr2);
        tablacontpr.addCell(contpr3);
        tablacontpr.addCell(contpr4);
        tablacontpr.addCell(contpr5);
        tablacontpr.addCell(contpr6);

        int totalCantidad = 0; 
        for (int i = 0; i < TablePrestamo.getRowCount(); i++) {
            String Numerop = TablePrestamo.getValueAt(i, 0).toString();
            String Fechap = TablePrestamo.getValueAt(i, 1).toString();
            String Descripcion = TablePrestamo.getValueAt(i, 2).toString();
            String Codigolib = TablePrestamo.getValueAt(i, 3).toString();
            String Cantidad = TablePrestamo.getValueAt(i, 4).toString();
            String Fechae = TablePrestamo.getValueAt(i, 5).toString();

            tablacontpr.addCell(Numerop);
            tablacontpr.addCell(Fechap);
            tablacontpr.addCell(Descripcion);
            tablacontpr.addCell(Codigolib);
            tablacontpr.addCell(Cantidad);
            tablacontpr.addCell(Fechae);

            
            totalCantidad += Integer.parseInt(Cantidad);
        }
        doc.add(tablacontpr);

        
        Paragraph totalLibros = new Paragraph();
        totalLibros.add(Chunk.NEWLINE);
        totalLibros.add("Cantidad total de librosa entregar: " + totalCantidad + "\n\n");
        doc.add(totalLibros);

        doc.close();
        archivo.close();
        Desktop.getDesktop().open(file);

    } catch (DocumentException | IOException e) {
        System.out.println(e.toString());
    }
    }
}



